// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExamationOnline.Models;

public partial class Class
{
    public int ClassId { get; set; }

    public string ClassName { get; set; }

    public string Description { get; set; }

    public bool? IsDelete { get; set; }

    public virtual ICollection<ClassUser> ClassUsers { get; set; } = new List<ClassUser>();

    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();
}