// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExamationOnline.Models;

public partial class ClassUser
{
    public int ClassId { get; set; }

    public int UserId { get; set; }

    public virtual Class Class { get; set; }

    public virtual User User { get; set; }
}