// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExamationOnline.Models;

public partial class Exam
{
    public string ExamId { get; set; }

    public string ExamName { get; set; }

    public int Duration { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? ClassId { get; set; }

    public int? SubjectId { get; set; }

    public int? TotalQuestion { get; set; }

    public bool? IsDisplayAnswer { get; set; }

    public int? StatusId { get; set; }

    public int? LectureId { get; set; }

    public bool? IsDelete { get; set; }

    public virtual Class Class { get; set; }

    public virtual ICollection<ExamQuestion> ExamQuestions { get; set; } = new List<ExamQuestion>();

    public virtual User Lecture { get; set; }

    public virtual StatusExam Status { get; set; }

    public virtual Subject Subject { get; set; }

    public virtual ICollection<UserAnswer> UserAnswers { get; set; } = new List<UserAnswer>();

    public virtual ICollection<UserExam> UserExams { get; set; } = new List<UserExam>();
}