// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExamationOnline.Models;

public partial class ExamQuestion
{
    public int Id { get; set; }

    public string ExamId { get; set; }

    public string QuestionId { get; set; }

    public virtual Exam Exam { get; set; }

    public virtual Question Question { get; set; }
}