// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExamationOnline.Models;

public partial class Option
{
    public int OptionId { get; set; }

    public string Content { get; set; }

    public bool? IsCorrect { get; set; }

    public string QuestionId { get; set; }

    public virtual Question Question { get; set; }

    public virtual ICollection<UserAnswer> UserAnswers { get; set; } = new List<UserAnswer>();
}