// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExamationOnline.Models;

public partial class SubjectUser
{
    public int SubjectId { get; set; }

    public int UserId { get; set; }

    public virtual Subject Subject { get; set; }

    public virtual User User { get; set; }
}